config/routes.rb
Rails.application.routes.draw do
  get 'lists/new'
  post 'lists' => 'lists#create' #create action
  get 'lists' => 'lists#index'
  get 'lists/show'
  get 'lists/edit'
  get 'top' => 'homes#top'
  get 'lists' => 'lists#index'
  get 'lists/:id' => 'lists#show', as: 'list'

  # root 'boards#index'
  get 'boards', to: 'boards#index'
  get 'boards/new', to: 'boards#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
  end

  def new
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new

    def create
      # １.&2. データを受け取り新規登録するためのインスタンス作成
      list = List.new(list_params)
      # 3. データをデータベースに保存するためのsaveメソッド実行
      list.save
      # 4. トップ画面へリダイレクト
      redirect_to '/lists'
    end
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
  end

  private
  # ストロングパラメータ
  def list_params
    params.require(:list).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  def top
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/boards/index.html.erb
<div class="d-flex align-items-center flex flex-ai-center flex-jc-between">
  <h1 class="head-1">掲示板一覧</h1>
  <div class="ml-auto boards__linkBox">
    <a href="/boards/new" class="btn btn-outline-dark">
      <button class="btn">新規作成</button>
    </a>
  </div>
</div>

<table class="table table-hover boards__table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>作成者</th>
      <th>作成日時</th>
      <th>更新日時</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>雑談掲示板</td>
      <td>Taro</td>
      <td>2018年4月1日</td>
      <td>2018年4月15日</td>
    </tr>
    <tr>
      <th>2</th>
      <td>雑談掲示板2</td>
      <td>Ken</td>
      <td>2018年4月1日</td>
      <td>2018年4月15日</td>
    </tr>
  </tbody>
</table>

app/views/boards/new.html.erb
<div class="d-flex align-items-center flex flex-ai-center flex-jc-between">
  <h1 class="head-1">掲示板作成</h1>
  <div class="ml-auto boards__linkBox">
    <a href="/boards" class="btn btn-outline-dark">
      <button class="btn">掲示板一覧</button>
    </a>
  </div>
</div>

<form>
  <div class="form-group">
    <label for="name">名前</label>
    <input id="name" class="form-control" />
  </div>
  <div class="form-group">
    <label for="title">タイトル</label>
    <input id="title" class="form-control" />
  </div>
  <div class="form-group">
    <label for="body">本文</label>
    <textarea id="body" class="form-control" rows="10"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">保存</button>
</form>

app/views/homes/top.html.erb
<h1>Hello Six</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track':
        'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <div class="wrap">
        <div class="container">
            <div class="inner-contents">
                <%= yield %>
            </div>
        </div>
    </div>
</body>

</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<div class="section">
  <div class="card">
    <h1>投稿一覧</h1>
    <% @lists.each do |list| %>
    <div class="row">
      <div class="column">
        <b>タイトル</b>
        <!-- "/lists/#{list.id}" -->
        <span> <%= link_to list.title, list_path(list.id) %> </span>
      </div>

      <div class="column">
        <b>内容</b>
        <span> <%= list.body %> </span>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="section">
  <div class="card">
    <h1>Post New</h1>
    <!-- 作成したListモデルをEachし、 フォームからPost出来るようにする -->
    <div class="row">
      <%= form_with model: List.new do |f| %>
      <div class="column">
        <h4>Title</h4>
        <%= f.text_field :title %>
      </div>

      <div class="column">
        <h4>Body</h4>
        <%= f.text_area :body %>
      </div>

      <div class="column"><%= f.submit '投稿' %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="section">
  <div class="card">
    <h1>投稿一覧</h1>
    <div class="row">
      <div class="column">
        <b>タイトル</b>
        <span> <%= @list.title %> </span>
      </div>

      <div class="column">
        <b>内容</b>
        <span> <%= @list.body %> </span>
      </div>
    </div>
  </div>
</div>